_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: False
  RESNETS:
    DEPTH: 50
  ROI_HEADS:
    NUM_CLASSES: 20
INPUT:
  MIN_SIZE_TRAIN: (480, 512, 544, 576, 608, 640, 672, 704, 736, 768, 800)
  MIN_SIZE_TEST: 600
DATASETS:
  CROSS_DATASET: True
  TRAIN: ('voc_2007_trainval', 'voc_2012_trainval')
  TRAIN_LABEL: ("voc_2007_trainval",)
  TRAIN_UNLABEL: ("voc_2012_trainval",)
  TEST: ('voc_2007_test',)
# SOLVER:
#   STEPS: (12000, 16000)
#   MAX_ITER: 18000  # 17.4 epochs
#   WARMUP_ITERS: 200
SOLVER:
  BASE_LR: 0.01
  STEPS: (24000, 32000)
  MAX_ITER: 36000  # 17.4*2 epochs
  WARMUP_ITERS: 200
# TEST:
#   EVAL_PERIOD: 2000
#   EVALUATOR: "COCOeval"