_BASE_: "../Base-RCNN-FPN.yaml"
MODEL:
  BACKBONE:
    NAME: "build_pseudolab_resnet_fpn_backbone"
  META_ARCHITECTURE: "TwoStagePseudoLabGeneralizedRCNN"
  WEIGHTS: "detectron2://ImageNetPretrained/MSRA/R-50.pkl"
  MASK_ON: True
  POINT_ON: True
  RESNETS:
    DEPTH: 50
  FPN:
    IN_FEATURES: ["res2", "res3", "res4", "res5"]
  PROPOSAL_GENERATOR:
    NAME: "PseudoLabRPN"
  RPN:
    POSITIVE_FRACTION: 0.25
    LOSS: "CrossEntropy"
  ROI_HEADS:
    NAME: "MILROIHeadsPseudoLab"
    LOSS: "FocalLoss"

  POINT_HEAD:
    NAME: "PointHeadPseudoLab"
#    NAME: "ImplicitPointHead"
    FC_DIM: 256
    NUM_FC: 1
    # IN_FEATURES: ["p2"]
    IN_FEATURES: ["res3", "res4", "res5"]
    NUM_CLASSES: 81
#    CLS_AGNOSTIC_MASK: False
#    TRAIN_NUM_POINTS: 196
#    SUBDIVISION_STEPS: 3
#    SUBDIVISION_NUM_POINTS: 784
#  IMPLICIT_POINTREND:
#    IMAGE_FEATURE_ENABLED: True
#    POS_ENC_ENABLED: True
#    PARAMS_L2_REGULARIZER: 0.00001
SOLVER:
  LR_SCHEDULER_NAME: "WarmupMultiStepLR"
  STEPS: (179990, 179995)
  MAX_ITER: 180000
  IMS_PER_BATCH_LABEL: 32
  IMS_PER_BATCH_UNLABEL: 32
  BASE_LR: 0.01
DATALOADER:
  SUP_PERCENT: 1.0
  RANDOM_DATA_SEED: 1
DATASETS:
  CROSS_DATASET: False
  TRAIN: ("coco_2017_train",)
  TEST: ("coco_2017_val",)
SEMISUPNET:
  Trainer: "pteacher"
  BBOX_THRESHOLD: 0.7
  TEACHER_UPDATE_ITER: 1
  BURN_UP_STEP: 2000
  EMA_KEEP_RATE: 0.9996
  UNSUP_LOSS_WEIGHT: 4.0
TEST:
  EVAL_PERIOD: 1000
  EVALUATOR: "COCOeval"
INPUT:
  # PointRend for instance segmentation does not work with "polygon" mask_format.
  MASK_FORMAT: "bitmask"
  # POINT_SUP: True
  SAMPLE_POINTS: 1
